name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install Rustfmt
        if: ${{ inputs.rustfmt == 'true' }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN_FORMAT }}
          components: rustfmt

      - name: Install Clippy
        if: ${{ inputs.clippy == 'true' }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN_LINT }}
          components: clippy

      - name: Install Solana
        if: ${{ inputs.solana == 'true' }}
        uses: solana-program/actions/install-solana@v1
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: true

      - name: Cache Cargo Dependencies
        if: ${{ inputs.cargo-cache-key && !inputs.cargo-cache-fallback-key }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ inputs.cargo-cache-key }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ inputs.cargo-cache-key }}

      - name: Cache Cargo Dependencies With Fallback
        if: ${{ inputs.cargo-cache-key && inputs.cargo-cache-fallback-key }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ inputs.cargo-cache-key }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.cargo-cache-key }}
            ${{ runner.os }}-${{ inputs.cargo-cache-fallback-key }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-${{ inputs.cargo-cache-fallback-key }}

      - name: Cache Local Cargo Dependencies
        if: ${{ inputs.cargo-cache-local-key }}
        uses: actions/cache@v4
        with:
          path: |
            .cargo/bin/
            .cargo/registry/index/
            .cargo/registry/cache/
            .cargo/git/db/
          key: ${{ runner.os }}-${{ inputs.cargo-cache-local-key }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ inputs.cargo-cache-local-key }}
